# Generated by Django 3.2.24 on 2024-02-08 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BillApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttrials',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BillApp.company'),
        ),
        migrations.AlterField(
            model_name='clienttrials',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
